### ISSUE TITLE
"RangeError: Invalid string length" while checking indentation

### ISSUE THREAD

**Issue by jmoses** [esatterwhite/eslint-plugin-sensible#9]
While linting against the attached file
[salt.spec.js.zip](https://github.com/esatterwhite/eslint-plugin-sensible/files/6076783/salt.spec.js.zip)

, I receive the following error:

```
  eslint:linter Filename: salt.spec.js +0ms
  eslint:linter Line: 1 +0ms
  eslint:linter Parser Options: { ecmaVersion: 10,
  sourceType: 'module',
  ecmaFeatures: { globalReturn: false } } +0ms
  eslint:linter Parser Path: espree +0ms
  eslint:linter Settings: {} +0ms
RangeError: Invalid string length
Occurred while linting /Users/jmoses/dev/logdna/pipeline-e2e/cypress/integration/api/endpoint/salt.spec.js:1
    at String.repeat (<anonymous>)
    at validateTokenIndent (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint-plugin-sensible/lib/rules/indent.js:759:49)
    at Program:exit.sourceCode.lines.forEach (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint-plugin-sensible/lib/rules/indent.js:1647:29)
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint-plugin-sensible/lib/rules/indent.js:1629:38)
    at listeners.(anonymous function).forEach.listener (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/jmoses/dev/logdna/pipeline-e2e/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
```

**Comment by jmoses** [comment]
Ah, the direct cause appears to have been the

```javascript
const body = 
  {
```
statement.
